name: Main

on:  
  push:
    tags:
      - 'v*'
      
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
            
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
          
      - name: Release
        uses: softprops/action-gh-release@v2
