name: Push package to Nuget.org
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    paths:
      - 'Vcr.HttpRecorder/**'

jobs:
  create_nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.11
      with:
        versionSpec: '6.0.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v3.1.11
    
    - name: Setup .NET 9.0 SDK for the Tests Project
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'


    - name: .NET Build
      run: dotnet build --configuration Release -p:Version=${{ env.GitVersion_SemVer }} -p:FileVersion=${{ env.GitVersion_AssemblySemVer }} -p:InformationalVersion=${{ env.GitVersion_InformationalVersion }}
      
    - name: .NET Test
      run: dotnet test --no-build --configuration Release --logger:trx

    - name: .NET Pack
      run: dotnet pack --no-build --configuration Release -p:Version=${{ env.GitVersion_FullSemVer }} --output ${{ github.workspace }}

    - name: Push nuget
      run: dotnet nuget push ${{github.workspace}}/*.nupkg --api-key ${{ secrets.NUGET_ORG_API_KEY }}
                    
